# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AFN' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AFN

pod 'AFNetworking'
pod 'Masonry'
pod 'JSONModel'
pod 'SDWebImage'

end
